server:
  port: 8003


#应用名称
spring:
  application:
    name: dcloud-link

#服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 8.137.146.165:8848
        username: nacos
        password: nacos


